### ISSUE TITLE
Error while installing using pip in kaggle

### ISSUE THREAD

**Issue by aymuos15** [tuttelikz/farabio#45]
## Instructions To Reproduce the Bug

1. What exact command you run:
```
!pip install farabio

```
Collecting farabio
  Using cached farabio-0.0.3-py3-none-any.whl (45 kB)
Collecting albumentations==1.0.3 (from farabio)
  Using cached albumentations-1.0.3-py3-none-any.whl (98 kB)
Collecting docutils==0.16 (from farabio)
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
Collecting jupyterlab==3.1.6 (from farabio)
  Using cached jupyterlab-3.1.6-py3-none-any.whl (8.6 MB)
Collecting matplotlib==3.4.3 (from farabio)
  Using cached matplotlib-3.4.3.tar.gz (37.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3031, in _dep_map
          return self.__dep_map
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2828, in __getattr__
          raise AttributeError(attr)
      AttributeError: _DistInfoDistribution__dep_map
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3022, in _parsed_pkg_info
          return self._pkg_info
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2828, in __getattr__
          raise AttributeError(attr)
      AttributeError: _pkg_info. Did you mean: 'egg_info'?
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-q_o17q4m/matplotlib_92c8f5accd244278bcac3c74bd7998e1/setup.py", line 258, in <module>
          setup(  # Finally, pass this all along to distutils to do the heavy lifting.
        File "/opt/conda/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 812, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 785, in resolve
          new_requirements = dist.requires(req.extras)[::-1]
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2749, in requires
          dm = self._dep_map
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3033, in _dep_map
          self.__dep_map = self._compute_dependencies()
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3042, in _compute_dependencies
          for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3024, in _parsed_pkg_info
          metadata = self.get_metadata(self.PKG_INFO)
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1412, in get_metadata
          value = self._get(path)
        File "/opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1616, in _get
          with open(path, 'rb') as stream:
      FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.10/site-packages/numpy-1.25.0.dist-info/METADATA'
      
      Edit setup.cfg to change the build options; suppress output with --quiet.
      
      BUILDING MATPLOTLIB
        matplotlib: yes [3.4.3]
            python: yes [3.10.12 | packaged by conda-forge | (main, Jun 23 2023,
                        22:40:32) [GCC 12.3.0]]
          platform: yes [linux]
             tests: no  [skipping due to configuration]
            macosx: no  [Mac OS-X only]
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

3. please simplify the steps as much as possible so they do not require additional resources to run, such as a private dataset.

To reproduce - simply run pip install farabio
## Environment:

Provide your environment information using the following command:
```
Kaggle
```

**Comment by tuttelikz** [comment]
Hi, @aymuos15; sorry for late response. Farabio, unfortunately, is not supported within Kaggle notebook environment for now..

**Comment by aymuos15** [comment]
No worries. Thank you for the update!
